version: "3.9"

services:
  frontend:
    build: ./frontend
    # volumes:
    # - ./frontend:/app
    ports:
      - 5173:5173
    networks:
      - default

  backend:
    build: ./backend
    # volumes:
    # - ./backend:/app
    ports:
      - 5180:5180
    networks:
      - default

networks:
  default:
    driver: bridge
