version: "3.9"

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173

    # backend:
    #   build: ./services/backend
    #   ports:
    #     - 5000:5000
    #   volumes:
    #     - ./services/backend:/app
    #   env_file:
    #     - ./services/ai/.env
    #   command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000

  backend:
    build: ./backend/
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - "tensorflow"
